title:        dictionary
url:          http://kin-lane.github.io/dictionary/
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 55
paginate_path: "/news/page:num"

production_url : http://kin-lane.github.io/dictionary/

BASE_PATH : http://kin-lane.github.io/dictionary/

categories_path : /categories.html
tags_path : /tags.html

org: Kin-Lane
repo: dictionary
resource: dictionary
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI
